apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watchtower
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "*" ]
    resources: [ "leases", "events" ]
    verbs: [ "*" ]
