apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watchtower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watchtower
subjects:
  - kind: ServiceAccount
    name: watchtower
    namespace: {{ .Release.Namespace }}
