apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: watchtower
  template:
    metadata:
      labels:
        app: watchtower
    spec:
      containers:
        - name: manager
          command: ["/app/manager"]
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: metric
              containerPort: 8083
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8084
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          env:
          - name: "ENABLE_LEADER_ELECTION"
            value: {{ required "A valid .Values.config.enableLeaderElection entry required!" .Values.config.enableLeaderElection | quote }}
          - name: "SYNC_PERIOD"
            value: {{ required "A valid .Values.config.syncPeriod entry required!" .Values.config.syncPeriod | quote }}
          - name: "WATCHER_REFRESH_PERIOD"
            value: {{ required "A valid .Values.config.watcherRefreshPeriod entry required!" .Values.config.watcherRefreshPeriod | quote }}
          {{- if .Values.extraEnvs }}
          {{ toYaml .Values.extraEnvs | indent 8 }}
          {{- end }}
      serviceAccountName: watchtower
      securityContext:
        runAsNonRoot: true
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      {{- end }}
      {{- if .Values.dockerconfigjson }}
      imagePullSecrets:
        - name: watchtower-pull-secret
      {{- end }}
