image:
  repository: ghcr.io/nccloud/mayfly
  tag: latest

replicas: 1

env: []

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"

tolerations: []
affinity: {}

serviceMonitor:
  enabled: false
  additionalLabels: {}

prometheusRule:
  enabled: false
  additionalLabels: {}
  builtInRules:
    reconcileErrors: true
    down: true
  additionalRules: []

imagePullSecretName: ""
dockerconfigjson: ""

config:
  taps: []
  sinks: []
  flows: []
