image:
  repository: ghcr.io/nccloud/mayfly
  tag: latest

replicas: 1

env: []

resources:
  limits:
    cpu: "500m"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "1Gi"

tolerations: []
affinity: {}

serviceMonitor:
  enabled: false
  additionalLabels: {}

prometheusRule:
  enabled: false
  additionalLabels: {}
  builtInRules:
    reconcileErrors: true
    down: true
  additionalRules: []

imagePullSecretName: ""
dockerconfigjson: ""

clusterRole:
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
