---
# -- override the chart name
# nameOverride: ""
# -- fully override the resource name
# fullnameOverride: ""

replicas: 1
harborApiUrl: 'http://harbor-harbor-harbor-core.harbor/api/v2.0'
exporterPort: 8000

# -- list of project/repositories to ignore (won't create a metric in prometheus)
# ignoreRepositories:
# - project/repo1
# - project/repo2

# -- name of an existing Secret with username and password keys; if set, harborUsername and harborPassword are ignored
existingSecret: ""

# -- script won't use credentials if values are empty read-only user should be enough
harborUsername: ''
harborPassword: ''

# -- additional environment variables to pass to the container
extraEnv: []
# -- number of threads for exporter script to call Harbor API
# - name: THREADS
#   value: "5"
# -- maximum number of characters to store in the description label, 0 means no limit
# - name: DESCRIPTION_MAX_LENGTH
#   value: "0"

image:
  repository: ghcr.io/nccloud/harbor-vulnerabilities-exporter
  tag: latest
  pullPolicy: IfNotPresent

# -- resource requests and limits for the exporter container
resources: {}
#  limits:
#    cpu: 200m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 64Mi

serviceMonitor:
  # -- serviceMonitor can be disabled if needed
  enabled: true
  scrapeTimeout: "30s"
  scrapeInterval: "300s"
