{{ if .Values.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: mayfly-pull-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{ end }}
