{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: mayfly
    {{- if .Values.serviceMonitor.additionalLabels }}
{{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
  name: mayfly
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - path: /metrics
      port: metric
      scheme: http
  selector:
    matchLabels:
      app: mayfly
{{- end }}
