apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata-reflector.serviceAccountName" . }}
  labels:
    {{- include "metadata-reflector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "metadata-reflector.selectorLabels" . | nindent 4 }}
