apiVersion: v2
name: zeropod
description: Kubernetes runtime for scaling containers to zero after a certain amount of time of the last TCP connection using CRIU checkpointing
type: application
version: 0.1.3
appVersion: v0.11.3
sources:
  - https://github.com/ctrox/zeropod
maintainers:
  - name: Scholzomat
    email: cloud@namecheap.com
