{{- if or .Values.manager.podUpdater .Values.manager.inPlaceScaling .Values.manager.statusLabels }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "zeropod.labels" . | nindent 4 }}
  name: {{ include "zeropod.fullname" . }}:pod-updater
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/resize
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "zeropod.labels" . | nindent 4 }}
  name: {{ include "zeropod.fullname" . }}:pod-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zeropod.fullname" . }}:pod-updater
subjects:
- kind: ServiceAccount
  name: {{ include "zeropod.fullname" . }}-node
  namespace: {{ .Release.Namespace }}
{{- end }}
