{{- if not .Values.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-vulnerabilities-exporter.name" . }}
  labels:
    {{- include "harbor-vulnerabilities-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.harborUsername | quote }}
  password: {{ .Values.harborPassword | quote }}
{{- end }}
