{{- if not .Values.existingSecret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-vulnerabilities-exporter.name" . }}
  labels:
    {{- include "harbor-vulnerabilities-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecret.usernameKey }}: {{ .Values.harborUsername | quote }}
  {{ .Values.existingSecret.passwordKey }}: {{ .Values.harborPassword | quote }}
{{- end }}
